Feat(loaderMongoRepository)[OCT-22]: implementation of work with mongo db in Loader Api
TheSpectreTeam/Octopus pull request #10
Opened 2022-05-24 10:10 UTC by VladiTitov

Changes made:
- created loader api
- implemented CRUD operations for dynamicEntity with mongo repository
- implemented mongo repository in CQRS pattern 
- added functional tests

2022-05-25 09:07 UTC, kogonidze requested changes

2022-05-25 09:07 UTC, kogonidze commented on src/Services/Loader/Api/Presentation/Loader.Presentation.WebApi/Middlewares/ErrorHandlerMiddleware.cs
> +    public class ErrorHandlerMiddleware
Nice

2022-05-25 11:22 UTC, VladiTitov commented on src/Services/Loader/Api/Core/Loader.Core.Application/Features/DynamicEntity/Queries/GetAllDynamicEntities/GetAllDynamicEntitiesQueryHandler.cs
> +            IMapper mapper,
Ooops, I'm fixed this.

2022-05-25 11:22 UTC, VladiTitov commented on src/Services/Loader/Api/Core/Loader.Core.Application/Behaviours/ValidationBehavior.cs
> +                    if (failures.Count != 0)
Good idea!

2022-05-25 11:25 UTC, VladiTitov commented on src/Services/Loader/Api/Core/Loader.Core.Application/Features/DynamicEntity/Commands/CreateDynamicEntity/CreateDynamicEntityCommandValidator.cs
> +                        .MinimumLength(1).WithMessage(ValidationMessages.DbNameInvalidLength);
Fixed this, changed to 2 characters.

2022-05-25 11:27 UTC, VladiTitov commented on src/Services/Loader/Api/Core/Loader.Core.Application/Features/DynamicEntity/Queries/GetDynamicEntityById/GetDynamicEntityQueryHandler.cs
> +            CancellationToken cancellationToken = default(CancellationToken))
It's base implementation `Handle()` method of MediatR library.

2022-05-25 11:29 UTC, VladiTitov commented on src/Services/Loader/Api/Core/Loader.Core.Application/Features/DynamicEntity/Queries/GetAllDynamicEntities/GetAllDynamicEntitiesQueryHandler.cs
> +        : IRequestHandler<GetAllDynamicEntitiesQuery, Response<IReadOnlyList<LoaderDynamicEntity>>>
I've used the CQRS pattern for data security, including using IReadOnlyList instead of List to make the returned data read-only.

2022-05-25 11:30 UTC, VladiTitov commented on src/Services/Loader/Tests/Loader.FunctionalTests/ApiTests/DynamicEntityEndpointsTests.cs
> +        #region GetAllEntitiesAsync
In my opinion, this is normal for tests, because I wrote them once and will rarely change them.

2022-05-26 06:40 UTC, kogonidze approved these changes
Well done!

2022-05-27 08:50 UTC, Anton-Sam approved these changes
Good job!

2022-05-27 10:51 UTC, merged