Feat(parserApi)[OCT-32]: tests for parser api
TheSpectreTeam/Octopus pull request #13
Opened 2022-06-09 12:08 UTC by kogonidze

2022-06-15 10:40 UTC, VladiTitov approved these changes
Good job!

2022-06-20 08:15 UTC, Anton-Sam requested changes

2022-06-20 08:15 UTC, Anton-Sam commented on src/Services/Parser/Api/Presentation/Parser.Presentation.WebApi/Endpoints/DynamicEntityEndpoints.cs
> +                pattern: "api/parserDynamicEntityModel",
Why do you prefer to use singular nouns instead of plural concept? There are common conventions that are used in all good REST APIs. One of such conventions is the use of plural nouns for defining resources.

2022-06-23 08:06 UTC, kogonidze commented on src/Services/Parser/Api/Presentation/Parser.Presentation.WebApi/Endpoints/DynamicEntityEndpoints.cs
> +                pattern: "api/parserDynamicEntityModel",
I agree with you, but in my case I have two endpoints for creation new entities: create one and create many. So if I will use plural concept by default, then I will use of course a plural noun for 'create many' endpoint and a single noun for 'create one'. And I suppose it can cause some non-obviousness, especially because it will be a plural noun for PUT and DELETE endpoints (I have not DeleteMany or UpdateMany). For example, for creation new entity you call POST method on `parserDynamicEntityModel` route, but for deletion this entity you call DELETE method on `parserDynamicEntityModels` route.

Probably more logical in this case to use singular concept, so the only one plural noun will be used for 'create many' endpoint.

2022-06-24 08:20 UTC, Anton-Sam approved these changes
Good job!

2022-06-27 06:39 UTC, merged