Feat[OCT-6]: creating dynamic entity service
TheSpectreTeam/Octopus pull request #2
Opened 2022-04-21 11:41 UTC by VladiTitov

Changes made:
- added services for DynamicEntity
- added common DynamicEntity models for project
- added unit tests for DynamicEntity string extensions

2022-04-21 12:49 UTC, kogonidze approved these changes

2022-04-21 12:49 UTC, kogonidze commented on src/BuildingBlocks/Common/Common.Models/DynamicEntity/DynamicEntityModel.cs
> +    }
Should we add here such properties like Separator, SkipLines?

2022-04-21 12:49 UTC, kogonidze commented on src/BuildingBlocks/Common/Common.Models/DynamicEntity/DynamicEntityModelBase.cs
> +    public class DynamicEntityModelBase
There is no any class that inherits from this base class. What class are you planning to inherit from this class?

2022-04-21 12:49 UTC, kogonidze commented on src/BuildingBlocks/DynamicEntity/DynamicEntity/Extensions/StringExtensions.cs
> +        }
As I understood this method not converts the string to camel case format. Because "fIRSTITEMINlist" will return "Firstiteminlist", not "FirstItemInList". So this method is more about "ToProperNoun"

2022-04-21 12:49 UTC, kogonidze commented on src/BuildingBlocks/DynamicEntity/DynamicEntity/Extensions/StringExtensions.cs
> +            return value;
I don't know what is better: to return default(int) value if we can't get valid int property from string or we should to throw an exception?

2022-04-21 14:44 UTC, VladiTitov commented on src/BuildingBlocks/Common/Common.Models/DynamicEntity/DynamicEntityModel.cs
> +    }
I think this should be added if necessary and after agreement

2022-04-21 14:51 UTC, VladiTitov commented on src/BuildingBlocks/Common/Common.Models/DynamicEntity/DynamicEntityModelBase.cs
> +    public class DynamicEntityModelBase
This class is used to create dynamic entities in the future in the DynamicEntityCreateService.

2022-04-21 18:07 UTC, Anton-Sam requested changes

2022-04-21 18:07 UTC, Anton-Sam commented on src/BuildingBlocks/DynamicEntity/DynamicEntity/Services/DynamicEntityCreateService.cs
> +                        property.SetValue(obj, objValues[index]);
What about decimal or double?

2022-04-21 18:10 UTC, VladiTitov commented on src/BuildingBlocks/DynamicEntity/DynamicEntity.Tests/Extensions/StringExtensionsTestingClass.cs
> +    public class StringExtensionsTestingClass
I don't think this is a fundamental change, but ok I'll change it

2022-04-21 18:12 UTC, VladiTitov commented on src/BuildingBlocks/DynamicEntity/DynamicEntity/Services/DynamicEntityCreateService.cs
> +                        property.SetValue(obj, objValues[index]);
We need these types in our implementations. I don't think it's necessary to describe all possible system types here, you can add them as needed.

2022-04-21 19:32 UTC, VladiTitov commented on src/BuildingBlocks/Common/Common.Models/DynamicEntity/DynamicEntityDataBaseProperty.cs
> +    public class DynamicEntityDataBaseProperty
fixed

2022-04-22 10:25 UTC, VladiTitov commented on src/BuildingBlocks/DynamicEntity/DynamicEntity/Extensions/StringExtensions.cs
> +            return value;
I removed those extensions as vestigial ones. I think that their implementation is not needed yet

2022-04-22 10:26 UTC, VladiTitov commented on src/BuildingBlocks/DynamicEntity/DynamicEntity/Services/DynamicEntityCreateService.cs
> +                .Select(value => GetObjectWithProperty(extendedType, value));
I removed this code and refactored the service

2022-04-25 10:08 UTC, Anton-Sam requested changes

2022-04-25 10:08 UTC, Anton-Sam commented on src/BuildingBlocks/DynamicEntity/DynamicEntity/Models/DynamicEntityMethodBuilder.cs
> +            Type? returnType = null)
Nice syntax, but why do you use it only in several places?

2022-04-25 14:18 UTC, kogonidze requested changes

2022-04-26 14:09 UTC, VladiTitov commented on src/BuildingBlocks/Common/Common.Models/DynamicEntity/DynamicEntityDataBaseProperty.cs
> +    public class DynamicEntityDatabaseProperty
fixed

2022-04-26 14:14 UTC, VladiTitov commented on src/BuildingBlocks/DynamicEntity/DynamicEntity/Models/DynamicEntityFieldBuilder.cs
> +                attributes: _fieldAttributes);
fixed

2022-04-26 14:14 UTC, VladiTitov commented on src/BuildingBlocks/DynamicEntity/DynamicEntity/Models/DynamicEntityMethodBuilder.cs
> +            => $"{methodName.ToLower()}_{base.PropertyField.GetValidPropertyName()}";
fixed

2022-04-26 18:14 UTC, VladiTitov commented on src/BuildingBlocks/DynamicEntity/DynamicEntity/Services/DynamicEntityPropertyService.cs
> +                attr: TypeAttributes.Public);
If you're talking about tabs - this is an IDE

2022-04-26 18:37 UTC, VladiTitov commented on src/BuildingBlocks/DynamicEntity/DynamicEntity/Models/DynamicEntityMethodBuilder.cs
> +            Type? returnType = null)
Because I arranged elvis symbols for those nullable types where null is expected

2022-04-26 18:39 UTC, VladiTitov commented on src/BuildingBlocks/DynamicEntity/DynamicEntity.Tests/Services/DynamicTypeFactoryTests.cs
> +            Assert.NotNull(actualType.GetField(dynamicEntityTestingModel.Properties.ToArray()[0].GetValidFieldName()));
fixed

2022-04-26 18:48 UTC, VladiTitov commented on src/BuildingBlocks/DynamicEntity/DynamicEntity.Tests/Services/DynamicTypeFactoryTests.cs
> +            var expected = dynamicEntityTestingModel.EntityName;
Answered above

2022-04-27 09:12 UTC, kogonidze approved these changes
Well done!

2022-04-27 11:00 UTC, Anton-Sam requested changes

2022-04-27 11:11 UTC, Anton-Sam requested changes

2022-04-27 11:11 UTC, Anton-Sam commented on src/BuildingBlocks/DynamicEntity/DynamicEntity/Models/DynamicEntityMethodBuilder.cs
> +        internal MethodAttributes MethodAttributes { get; }
What about private readonly field?

2022-04-27 11:11 UTC, Anton-Sam commented on src/BuildingBlocks/DynamicEntity/DynamicEntity/Models/DynamicEntityPropertyBuilder.cs
> +        internal PropertyBuilder PropertyBuilder { get; }
It looks like private readonly field.

2022-04-27 11:11 UTC, Anton-Sam commented on src/BuildingBlocks/DynamicEntity/DynamicEntity/Abstractions/IDynamicTypeFactory.cs
> +﻿using Common.Models.DynamicEntity;
Unnecessary using

2022-04-27 11:11 UTC, Anton-Sam commented on src/BuildingBlocks/DynamicEntity/DynamicEntity.Tests/Extensions/DynamicEntityModelPropertyExtensionsTests.cs
> +                Comment = default(string),
Unnecessary definitions again.

2022-04-27 12:16 UTC, VladiTitov commented on src/BuildingBlocks/DynamicEntity/DynamicEntity.Tests/Extensions/DynamicEntityModelPropertyExtensionsTests.cs
> +                Comment = default(string),
fixed

2022-04-27 12:16 UTC, VladiTitov commented on src/BuildingBlocks/DynamicEntity/DynamicEntity/Abstractions/IDynamicTypeFactory.cs
> +﻿using Common.Models.DynamicEntity;
fixed

2022-04-27 12:17 UTC, VladiTitov commented on src/BuildingBlocks/DynamicEntity/DynamicEntity/Models/DynamicEntityMethodBuilder.cs
> +        internal MethodAttributes MethodAttributes { get; }
Why didn't these questions come up before? Fixed

2022-04-27 12:17 UTC, VladiTitov commented on src/BuildingBlocks/DynamicEntity/DynamicEntity/Models/DynamicEntityMethodBuilder.cs
> +        internal MethodAttributes MethodAttributes { get; }
Answered before

2022-04-27 12:17 UTC, VladiTitov commented on src/BuildingBlocks/DynamicEntity/DynamicEntity/Models/DynamicEntityPropertyBuilder.cs
> +        internal PropertyBuilder PropertyBuilder { get; }
Answered before

2022-04-27 12:45 UTC, Anton-Sam approved these changes
Good job!

2022-04-27 12:49 UTC, merged