Feat(mongoRepository)[OCT-5]: creating repository for MongoDb
TheSpectreTeam/Octopus pull request #4
Opened 2022-05-06 09:56 UTC by VladiTitov

Changes made:
- added base repository for project
- implemented repository for MongoDb
- added tests for MongoDb repository

2022-05-06 14:19 UTC, kogonidze requested changes

2022-05-06 14:19 UTC, kogonidze commented on src/BuildingBlocks/Repositories/Repository.MongoDb/Repositories/MongoRepository.cs
> +            if (id is ObjectId i)
Why don't you want to use here construction 'as'?

2022-05-07 10:51 UTC, VladiTitov commented on src/BuildingBlocks/Repositories/Repository.MongoDb/Repositories/MongoRepository.cs
> +            if (id is ObjectId i)
Because in the case of using `as` I need to check for null, the new implementation of `is` since c# 7 allows you to type match and return it on success to use, in my case the variable `i`. This allows you to shorten the code and increase its readability.

2022-05-09 08:19 UTC, Anton-Sam approved these changes
Good job!

2022-05-09 08:19 UTC, Anton-Sam commented on src/BuildingBlocks/Repositories/Repository.MongoDb/Repositories/MongoRepository.cs
> +            if (id is ObjectId i)
You can use 'as' statement with ?? operator. Something like this: var a=val as type ?? throw new ... It looks more elegant and allows you to avoid 'if' statement.

2022-05-09 09:38 UTC, VladiTitov commented on src/BuildingBlocks/Repositories/Repository.MongoDb/Repositories/MongoRepository.cs
> +            if (id is ObjectId i)
Yes, I understand, perhaps it would be more readable, but ObjectId is a structure, as far as I know, the `as` operator only works with reference types.

2022-05-09 09:45 UTC, VladiTitov commented on src/BuildingBlocks/Repositories/Repository.MongoDb/Abstractions/IMongoDbConfiguration.cs
> +        string? DatabaseName { get; set; }
fixed

2022-05-09 09:45 UTC, VladiTitov commented on src/BuildingBlocks/Repositories/Repository.MongoDb/Models/MongoDbConfiguration.cs
> +        public string? DatabaseName { get; set; } = "local";
fixed

2022-05-09 09:52 UTC, kogonidze approved these changes

2022-05-09 09:55 UTC, merged